@baseUrl = http://localhost:3001
@apiEndpoint = {{baseUrl}}/api
@blogsEndpoint = {{apiEndpoint}}/blogs
@json = application/json

### Be Sure to assign value to variables below 
### before sending request to any endpoint requireing it 

@authToken = 
@blogId = 

###

GET {{blogsEndpoint}}
accept: {{json}} 

###

GET {{blogsEndpoint}}/{{blogId}}
accept: {{json}} 

###

POST {{blogsEndpoint}}
Content-Type:{{json}} 
Authorization: Bearer {{authToken}} 
accept: {{json}}

{
  "title": "test blog 7",
  "url": "testurl.com 6",
  "likes": 1006
}

###

PUT {{blogsEndpoint}}/{{blogId}}
Authorization: Bearer {{authToken}}
Content-Type:{{json}} 
accept: {{json}} 

{
  "likes": 5003
}

###

DELETE {{blogsEndpoint}}/{{blogId}}
Authorization: Bearer {{authToken}}
accept: {{json}} 

### 

GET {{baseUrl}}/nonExistingEndPoint
accept: {{json}}

