@baseUrl = http://localhost:3001
@apiEndpoint = {{baseUrl}}/api
@blogsEndpoint = {{apiEndpoint}}/blogs
@blogId = 66967060c69fe941392cb74f
@json = application/json

GET {{blogsEndpoint}}
accept: {{json}} 

###

GET {{blogsEndpoint}}/{{blogId}}
accept: {{json}} 

###

POST {{blogsEndpoint}}
Content-Type:{{json}} 
accept: {{json}}

{
  "title": "test blog 3",
  "author": "test author 3",
  "url": "testurl.com 3",
  "likes": 1003
}

###

GET {{baseUrl}}/nonExistingEndPoint
accept: {{json}}

